/* Oiseaux d'Ouessant — tous les textes de l'appli, en français (fr) et en anglais (en).
   Pour corriger une phrase, il suffit de la modifier ici. ${…} insère une valeur calculée par l'appli. */
window.OUESSANT_ETAT = window.OUESSANT_ETAT || { cvd: false };   // mode daltonisme, mis à jour par l'appli
window.OUESSANT_TEXTES = {
    fr: {
      docTitle: "Oiseaux d'Ouessant · canal de diffusion",
      title: "Oiseaux d'Ouessant",
      lede: "Tape le nom d'une espèce pour savoir sur quel canal annoncer ton observation.",
      placeholder: 'Nom français, scientifique ou anglais',
      searchLabel: 'Rechercher une espèce',
      clear: 'Effacer', all: 'Toutes', showSsp: 'Afficher les sous-espèces', ssp: 'sous-espèce',
      channelsLabel: 'Filtrer par canal de diffusion',
      loading: 'Chargement de la liste des espèces…',
      found: 'Espèce trouvée', noMatch: 'Aucune espèce ne correspond pour l’instant.',
      near: n => n + ' nom' + (n>1?'s':'') + ' proche' + (n>1?'s':''),
      count: (n, filtered) => n + ' taxon' + (n>1?'s':'') + (filtered ? ' sur ce canal' : ''),
      fuzzyNear: q => `Aucune espèce ne s'appelle exactement « ${q} ». Vérifie l'orthographe parmi les noms proches ci-dessous. Si ce n'est aucun d'eux, ce serait probablement une première pour l'île : <strong>annonce-la sur Telegram</strong>.`,
      fuzzyNone: q => `« ${q} » n'est pas dans la liste des espèces déjà vues sur l'île. Vérifie l'orthographe ; si elle est juste, ce serait probablement une première pour Ouessant : <strong>annonce-la sur Telegram</strong>.`,
      sourceGithub: 'Liste à jour', listsOf: d => `listes du ${d}`, sourceSaved: 'Copie enregistrée dans ce navigateur', sourceFile: 'Fichier importé',
      sourceCount: (sp, ssp) => sp + ' espèces' + (ssp ? ' et ' + ssp + ' sous-espèces' : ''),
      importTitle: 'Ajoute la liste des espèces',
      importText: "La liste n'a pas pu être téléchargée depuis GitHub sur cette page. Importe le fichier <em>ouessant_birds.json</em> depuis ton ordinateur ou ton téléphone : il restera enregistré dans ce navigateur.",
      importBtn: 'Importer le fichier JSON', importOther: 'Importer un autre fichier JSON',
      badFile: "Ce fichier n'est pas lisible. Il doit contenir une liste d'espèces avec au moins les champs « Nom Français », « Nom Scientifique » et « Proposition de Canal de Diffusion Ouessant ».",
      channels: { telegram: 'Alerte Telegram', whatsapp: 'Alerte WhatsApp', none: "Pas d'alerte", unknown: 'Non renseigné' },
      tabBirds: 'Oiseaux', tabPlaces: 'Lieux', tabWhere: 'Où suis-je ?',
      phareLabel: 'Météo et partage', phareOff: 'Hors connexion : le phare est éteint (météo indisponible)', wOffline: 'Pas de connexion : la météo reviendra avec le réseau.', wTitle: 'Météo à Ouessant', wLoading: 'Chargement de la météo…', wErr: 'Météo indisponible pour le moment (connexion ?).',
      wNow: (dir, kmh, bf) => `Vent ${dir}, ${kmh} km/h (force ${bf})`, wGust: g => `rafales ${g} km/h`, wSrc: 'Météo : Open-Meteo.com, mise à jour toutes les 15 minutes.',
      dirs16: ['du nord','du nord-nord-est','du nord-est',"d'est-nord-est","d'est","d'est-sud-est",'du sud-est','du sud-sud-est','du sud','du sud-sud-ouest','du sud-ouest',"d'ouest-sud-ouest","d'ouest","d'ouest-nord-ouest",'du nord-ouest','du nord-nord-ouest'],
      dirsShort: ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSO','SO','OSO','O','ONO','NO','NNO'],
      today: "Aujourd'hui", tomorrow: 'Demain',
      shTitle: "Partager l'appli", shText: "Fais scanner ce QR code à un autre observateur : il ouvrira l'appli directement.",
      shBtn: 'Partager…', shCopy: 'Copier le lien', shCopied: 'Lien copié !', qrErr: 'QR code indisponible hors connexion.',
      egg: n => `Alerte Telegram ! ${n} vient de passer devant le phare du Créac'h.`, eggNone: "Un oiseau vient de passer devant le phare du Créac'h !",
      wx: { 0: 'ciel dégagé', 1: 'peu nuageux', 2: 'partiellement nuageux', 3: 'couvert', 45: 'brouillard', 48: 'brouillard givrant', 51: 'bruine légère', 53: 'bruine', 55: 'bruine forte',
            56: 'bruine verglaçante', 57: 'bruine verglaçante', 61: 'pluie faible', 63: 'pluie', 65: 'forte pluie', 66: 'pluie verglaçante', 67: 'pluie verglaçante',
            71: 'neige faible', 73: 'neige', 75: 'forte neige', 77: 'grains de neige', 80: 'averses', 81: 'averses', 82: 'fortes averses', 85: 'averses de neige', 86: 'averses de neige',
            95: 'orage', 96: 'orage avec grêle', 99: 'orage avec grêle' },
      prefsLabel: 'Affichage', themeLabel: 'Thème', tAuto: 'Auto', tLight: 'Clair', tDark: 'Sombre',
      colorsLabel: 'Couleurs', cStd: 'Standard', cCvd: 'Daltonisme',
      cvdNote: "« Daltonisme » utilise des couleurs distinguables par la plupart des personnes daltoniennes. « Auto » suit le réglage du téléphone.",
      ledeWhere: 'Trouve les 5 lieux-dits les plus proches de ta position.',
      locateBtn: 'Me localiser', relocateBtn: 'Actualiser ma position',
      youAre: (c, a) => `Tu es dans le carré ${c} (précision GPS ± ${a} m). Les 5 lieux-dits les plus proches :`,
      notHere: d => `Tu ne sembles pas être sur Ouessant : le lieu-dit le plus proche est à ${d}.`,
      dirs: ['N', 'NE', 'E', 'SE', 'S', 'SO', 'O', 'NO'],
      checkedShort: 'position vérifiée',
      whereCaption: c => `Ta position (point ${window.OUESSANT_ETAT.cvd ? 'rose' : 'bleu'}) dans le carré ${c}, et les lieux-dits numérotés.`,
      whereNote: "Les distances sont approximatives : la plupart des lieux-dits sont placés au centre de leur carré sur la carte (± 100 m). Ta position n'est envoyée nulle part.",
      ledePlaces: "Cherche un lieu-dit de l'île pour obtenir ses coordonnées GPS <strong>INDICATIVES</strong>.",
      locTip: "« Loc SVP » reste le meilleur moyen de savoir où aller.",
      openIslandMap: "Ouvrir la carte de l'île (PDF)",
      mapCaption: c => `${c.length > 1 ? 'Carrés' : 'Carré'} ${c.join(', ')} encadré${c.length > 1 ? 's' : ''} en ${window.OUESSANT_ETAT.cvd ? 'bleu' : 'rouge'}, extrait de la carte de l'Association Naturaliste d'Ouessant.`,
      mapLoading: 'Chargement de la carte…',
      verified: 'Position vérifiée sur le terrain',
      suggest: 'Proposer une meilleure position', suggestGps: 'Je suis sur place : envoyer ma position GPS',
      sHelp: "Le nouveau point doit se trouver dans l'un des carrés affichés ci-dessus.",
      useGps: 'Utiliser ma position GPS (sur place)',
      gpsWait: 'Recherche de ta position…',
      gpsErr: 'Position GPS indisponible. Autorise la localisation ou colle des coordonnées.',
      gpsAcc: m => `Position GPS obtenue (précision ± ${m} m).` + (m > 100 ? ' Précision faible : attends quelques secondes à découvert et réessaie.' : ''),
      pasteLabel: 'ou colle des coordonnées',
      commentLabel: 'Commentaire (facultatif)',
      check: 'Vérifier le point',
      badFormat: 'Coordonnées illisibles. Exemple : 48.45606, -5.08603',
      okIn: (c, d) => `Le point est bien dans la zone (carré ${c}), à ${d} de la position actuelle.`,
      outZone: (c, n) => c ? `Ce point est dans le carré ${c}, en dehors des carrés affichés : il est trop loin de « ${n} ». Vérifie les coordonnées.` : "Ce point est en dehors de la carte d'Ouessant. Vérifie les coordonnées.",
      sendOff: "L'envoi des propositions est momentanément indisponible.",
      sendForm: 'Envoyer la proposition',
      proposeEdit: 'Proposer une modification', newBird: 'Proposer un nouvel oiseau', newBirdQ: 'Proposer cet oiseau ?',
      bHelpEdit: 'Corrige les champs nécessaires, puis prépare la proposition. Explique ton choix en commentaire si besoin.',
      bHelpNew: 'Une espèce ou sous-espèce manque à la liste ? Renseigne-la : elle sera ajoutée après vérification.',
      fFR: 'Nom français', fSCI: 'Nom scientifique', fEN: 'Nom anglais (facultatif)', fType: 'Type de taxon', fCanal: 'Canal de diffusion',
      typeSp: 'espèce', typeSsp: 'sous-espèce', choose: '— choisir —', prep: 'Préparer la proposition',
      needFrSci: 'Le nom français et le nom scientifique sont obligatoires.', needCanal: 'Choisis un canal de diffusion.',
      noChange: 'Aucune modification : change au moins un champ, ou explique-toi en commentaire.',
      bDup: n => `« ${n} » est déjà dans la liste. Cherche-le, puis utilise « Proposer une modification ».`,
      bClash: n => `Ce nom est déjà utilisé par « ${n} ».`,
      changes: 'Modifications proposées :', commentOnly: 'Aucun champ modifié : seul ton commentaire sera envoyé.',
      bNewOk: n => `« ${n} » est prêt à être proposé.`,
      newPlace: 'Proposer un nouveau lieu-dit', newPlaceQ: 'Proposer ce lieu-dit ?',
      newHelp: "Un lieu-dit manque à la liste ? Donne son nom et sa position : il sera ajouté après vérification.",
      newName: 'Nom du lieu-dit',
      newNoName: 'Indique le nom du lieu-dit.',
      newDup: n => `« ${n} » est déjà dans la liste. Pour corriger sa position, ouvre-le et utilise « Proposer une meilleure position ».`,
      newOut: "Ce point est en dehors de la carte d'Ouessant. Vérifie les coordonnées.",
      newOk: (n, c) => `« ${n} » serait placé dans le carré ${c}. Vérifie sur la carte ci-dessous, puis envoie ta proposition.`,
      newCaption: (n, c) => `Position proposée pour « ${n} » (losange vert), carré ${c}.`,
      formNote: "Le formulaire va s'ouvrir, déjà rempli : il ne reste qu'à cliquer sur « Envoyer ». Ta proposition sera vérifiée, puis la mise à jour sera prise en compte dans les prochains jours.",
      mapMissing: "Aperçu indisponible : le fichier carte_ouessant.jpg est introuvable à côté de l'appli.",
      pPlaceholder: 'Nom du lieu (ex. Pern, Stiff, Kadoran)', pLabel: 'Rechercher un lieu',
      pCount: n => n + ' lieu' + (n>1?'x':''), pNone: q => `Aucun lieu ne correspond à « ${q} ».`,
      square: n => n > 1 ? 'Carrés' : 'Carré', approx: m => `Position approximative : ± ${m} m (centre du carré sur la carte)`,
      approxPlaced: m => `Position approximative : ± ${m} m (point placé sur la carte, non vérifié sur le terrain)`,
      exact: 'Position exacte', copy: 'Copier', copied: 'Copié !', openMap: 'Ouvrir dans Maps',
      placesNote: "Coordonnées calculées d'après la carte de l'île de l'Association Naturaliste d'Ouessant : chaque lieu est placé au centre de son carré, d'où une précision d'environ 500 m. Seuls les phares ont une position exacte. Vérifie sur le terrain avant de donner un point précis."
    },
    en: {
      docTitle: 'Birds of Ouessant · where to report',
      title: 'Birds of Ouessant',
      lede: 'Type a species name to find out which channel to report your sighting.',
      placeholder: 'English, French or scientific name',
      searchLabel: 'Search for a species',
      clear: 'Clear', all: 'All', showSsp: 'Show subspecies', ssp: 'subspecies',
      channelsLabel: 'Filter by reporting channel',
      loading: 'Loading the species list…',
      found: 'Species found', noMatch: 'No matching species yet.',
      near: n => n + ' similar name' + (n>1?'s':''),
      count: (n, filtered) => n + (n>1 ? ' taxa' : ' taxon') + (filtered ? ' on this channel' : ''),
      fuzzyNear: q => `No species is called exactly “${q}”. Check the spelling against the similar names below. If it is none of them, it would probably be a first for the island: <strong>report it on Telegram</strong>.`,
      fuzzyNone: q => `“${q}” is not on the list of species already recorded on the island. Check the spelling; if it is correct, it would probably be a first for Ouessant: <strong>report it on Telegram</strong>.`,
      sourceGithub: 'Up-to-date list', listsOf: d => `lists of ${d}`, sourceSaved: 'Copy saved in this browser', sourceFile: 'Imported file',
      sourceCount: (sp, ssp) => sp + ' species' + (ssp ? ' and ' + ssp + ' subspecies' : ''),
      importTitle: 'Add the species list',
      importText: 'The list could not be downloaded from GitHub on this page. Import the <em>ouessant_birds.json</em> file from your computer or phone: it will stay saved in this browser.',
      importBtn: 'Import the JSON file', importOther: 'Import another JSON file',
      badFile: 'This file cannot be read. It must contain a list of species with at least the fields “Nom Français”, “Nom Scientifique” and “Proposition de Canal de Diffusion Ouessant”.',
      channels: { telegram: 'Telegram alert', whatsapp: 'WhatsApp alert', none: 'No alert', unknown: 'Not specified' },
      tabBirds: 'Birds', tabPlaces: 'Places', tabWhere: 'Where am I?',
      phareLabel: 'Weather and sharing', phareOff: 'Offline: the lighthouse is off (no weather)', wOffline: 'No connection: the weather will be back with the network.', wTitle: 'Weather on Ouessant', wLoading: 'Loading the weather…', wErr: 'Weather unavailable right now (connection?).',
      wNow: (dir, kmh, bf) => `Wind ${dir}, ${kmh} km/h (force ${bf})`, wGust: g => `gusts ${g} km/h`, wSrc: 'Weather: Open-Meteo.com, updated every 15 minutes.',
      dirs16: ['from the N','from the NNE','from the NE','from the ENE','from the E','from the ESE','from the SE','from the SSE','from the S','from the SSW','from the SW','from the WSW','from the W','from the WNW','from the NW','from the NNW'],
      dirsShort: ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW'],
      today: 'Today', tomorrow: 'Tomorrow',
      shTitle: 'Share the app', shText: 'Let another birder scan this QR code: it opens the app straight away.',
      shBtn: 'Share…', shCopy: 'Copy link', shCopied: 'Link copied!', qrErr: 'QR code unavailable offline.',
      egg: n => `Telegram alert! ${n} just flew past the Créac'h lighthouse.`, eggNone: "A bird just flew past the Créac'h lighthouse!",
      wx: { 0: 'clear sky', 1: 'mainly clear', 2: 'partly cloudy', 3: 'overcast', 45: 'fog', 48: 'freezing fog', 51: 'light drizzle', 53: 'drizzle', 55: 'heavy drizzle',
            56: 'freezing drizzle', 57: 'freezing drizzle', 61: 'light rain', 63: 'rain', 65: 'heavy rain', 66: 'freezing rain', 67: 'freezing rain',
            71: 'light snow', 73: 'snow', 75: 'heavy snow', 77: 'snow grains', 80: 'showers', 81: 'showers', 82: 'heavy showers', 85: 'snow showers', 86: 'snow showers',
            95: 'thunderstorm', 96: 'thunderstorm with hail', 99: 'thunderstorm with hail' },
      prefsLabel: 'Display', themeLabel: 'Theme', tAuto: 'Auto', tLight: 'Light', tDark: 'Dark',
      colorsLabel: 'Colours', cStd: 'Standard', cCvd: 'Colour-blind',
      cvdNote: '“Colour-blind” uses colours most colour-blind people can tell apart. “Auto” follows your phone’s setting.',
      ledeWhere: 'Find the 5 place names closest to where you are.',
      locateBtn: 'Locate me', relocateBtn: 'Update my position',
      youAre: (c, a) => `You are in square ${c} (GPS accuracy ± ${a} m). The 5 closest place names:`,
      notHere: d => `You don’t seem to be on Ouessant: the closest place name is ${d} away.`,
      dirs: ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'],
      checkedShort: 'position checked',
      whereCaption: c => `Your position (${window.OUESSANT_ETAT.cvd ? 'pink' : 'blue'} dot) in square ${c}, and the numbered place names.`,
      whereNote: 'Distances are approximate: most place names sit at the centre of their map square (± 100 m). Your position is not sent anywhere.',
      ledePlaces: 'Search for a place name on the island to get its <strong>INDICATIVE</strong> GPS coordinates.',
      locTip: 'Asking “Loc SVP” (location please) in the group is still the best way to know where to go.',
      openIslandMap: 'Open the island map (PDF)',
      mapCaption: c => `${c.length > 1 ? 'Squares' : 'Square'} ${c.join(', ')} outlined in ${window.OUESSANT_ETAT.cvd ? 'blue' : 'red'}, from the map by the Association Naturaliste d’Ouessant.`,
      mapLoading: 'Loading the map…',
      verified: 'Position checked on the ground',
      suggest: 'Suggest a better position', suggestGps: 'I am on site: send my GPS position',
      sHelp: 'The new point must lie within one of the squares shown above.',
      useGps: 'Use my GPS position (on site)',
      gpsWait: 'Getting your position…',
      gpsErr: 'GPS position unavailable. Allow location access or paste coordinates.',
      gpsAcc: m => `GPS position found (accuracy ± ${m} m).` + (m > 100 ? ' Low accuracy: wait a few seconds in the open and try again.' : ''),
      pasteLabel: 'or paste coordinates',
      commentLabel: 'Comment (optional)',
      check: 'Check the point',
      badFormat: 'Coordinates not recognised. Example: 48.45606, -5.08603',
      okIn: (c, d) => `The point is within the area (square ${c}), ${d} from the current position.`,
      outZone: (c, n) => c ? `This point is in square ${c}, outside the squares shown: it is too far from “${n}”. Check the coordinates.` : 'This point is outside the Ouessant map. Check the coordinates.',
      sendOff: 'Sending suggestions is temporarily unavailable.',
      sendForm: 'Send the suggestion',
      proposeEdit: 'Suggest a change', newBird: 'Suggest a new bird', newBirdQ: 'Suggest this bird?',
      bHelpEdit: 'Correct the fields as needed, then prepare the suggestion. Explain your choice in a comment if useful.',
      bHelpNew: 'Is a species or subspecies missing from the list? Fill it in: it will be added after checking.',
      fFR: 'French name', fSCI: 'Scientific name', fEN: 'English name (optional)', fType: 'Taxon type', fCanal: 'Reporting channel',
      typeSp: 'species', typeSsp: 'subspecies', choose: '— choose —', prep: 'Prepare the suggestion',
      needFrSci: 'The French and scientific names are required.', needCanal: 'Choose a reporting channel.',
      noChange: 'No change: edit at least one field, or explain in a comment.',
      bDup: n => `“${n}” is already on the list. Search for it, then use “Suggest a change”.`,
      bClash: n => `This name is already used by “${n}”.`,
      changes: 'Suggested changes:', commentOnly: 'No field changed: only your comment will be sent.',
      bNewOk: n => `“${n}” is ready to be suggested.`,
      newPlace: 'Suggest a new place name', newPlaceQ: 'Suggest this place name?',
      newHelp: 'Is a place name missing from the list? Give its name and position: it will be added after checking.',
      newName: 'Place name',
      newNoName: 'Enter the place name.',
      newDup: n => `“${n}” is already on the list. To correct its position, open it and use “Suggest a better position”.`,
      newOut: 'This point is outside the Ouessant map. Check the coordinates.',
      newOk: (n, c) => `“${n}” would be placed in square ${c}. Check on the map below, then send your suggestion.`,
      newCaption: (n, c) => `Suggested position for “${n}” (green diamond), square ${c}.`,
      formNote: 'The form will open already filled in: just press “Submit”. Your suggestion will be checked, and the update will be applied within the next few days.',
      mapMissing: 'Preview unavailable: the file carte_ouessant.jpg cannot be found next to the app.',
      pPlaceholder: 'Place name (e.g. Pern, Stiff, Kadoran)', pLabel: 'Search for a place',
      pCount: n => n + ' place' + (n>1?'s':''), pNone: q => `No place matches “${q}”.`,
      square: n => n > 1 ? 'Squares' : 'Square', approx: m => `Approximate position: ± ${m} m (centre of the map square)`,
      approxPlaced: m => `Approximate position: ± ${m} m (point placed on the map, not checked on the ground)`,
      exact: 'Exact position', copy: 'Copy', copied: 'Copied!', openMap: 'Open in Maps',
      placesNote: 'Coordinates derived from the island map by the Association Naturaliste d’Ouessant: each place sits at the centre of its map square, so accuracy is about 500 m. Only the lighthouses have an exact position. Check on the ground before giving a precise spot.'
    }
  };
