/* Oiseaux d'Ouessant — tous les textes de l'appli, en français (fr) et en anglais (en).
   Pour corriger une phrase, il suffit de la modifier ici. ${…} insère une valeur calculée par l'appli. */
window.OUESSANT_ETAT = window.OUESSANT_ETAT || { cvd: false };   // mode daltonisme, mis à jour par l'appli
window.OUESSANT_TEXTES = {
    fr: {
      docTitle: "Oiseaux d'Ouessant · canal de diffusion",
      title: "Oiseaux d'Ouessant",
      lede: "Tape le nom d'une espèce pour savoir sur quel canal annoncer ton observation, puis touche le canal pour préparer ton message.",
      placeholder: 'Nom français, scientifique ou anglais',
      searchLabel: 'Rechercher une espèce',
      clear: 'Effacer', all: 'Toutes', showSsp: 'Afficher les sous-espèces', ssp: 'sous-espèce',
      channelsLabel: 'Filtrer par canal de diffusion',
      loading: 'Chargement de la liste des espèces…',
      found: 'Espèce trouvée', noMatch: 'Aucune espèce ne correspond pour l’instant.',
      near: n => n + ' nom' + (n>1?'s':'') + ' proche' + (n>1?'s':''),
      count: (n, filtered) => n + ' taxon' + (n>1?'s':'') + (filtered ? ' sur ce canal' : ''),
      fuzzyNear: q => `Aucune espèce ne s'appelle exactement « ${q} ». Vérifie l'orthographe parmi les noms proches ci-dessous. Si ce n'est aucun d'eux, ce serait probablement une première pour l'île : <strong>annonce-la sur Telegram</strong>.`,
      fuzzyNone: q => `« ${q} » n'est pas dans la liste des espèces déjà vues sur l'île. Vérifie l'orthographe ; si elle est juste, ce serait probablement une première pour Ouessant : <strong>annonce-la sur Telegram</strong>.`,
      sourceGithub: 'Liste à jour', listsOf: d => `listes du ${d}`, listsOfBoth: (b, p) => `oiseaux du ${b}, lieux du ${p}`, sourceSaved: 'Copie enregistrée dans ce navigateur', sourceFile: 'Fichier importé',
      sourceCount: (sp, ssp) => sp + ' espèces' + (ssp ? ' et ' + ssp + ' sous-espèces' : ''),
      importTitle: 'Ajoute la liste des espèces',
      importText: "La liste n'a pas pu être téléchargée depuis GitHub sur cette page. Importe le fichier <em>ouessant_birds.json</em> depuis ton ordinateur ou ton téléphone : il restera enregistré dans ce navigateur.",
      importBtn: 'Importer le fichier JSON', legalBtn: 'Informations légales', guideLink: "Guide d'utilisation (PDF)", editorLinkT: 'Éditeur des listes', contactLink: 'Une question, un retour ?', contactLabel: 'Ton message (question, idée, problème…)', contactSend: 'Continuer vers le formulaire', contactHelp: "Ton message est anonyme. Le formulaire s'ouvre avec ton message déjà rempli : il ne reste qu'à cliquer sur « Envoyer ». Si tu veux une réponse, indique dans ton message comment te joindre.", contactEmpty: 'Écris d’abord ton message.', azLabel: 'Accès rapide par lettre',
      legalHtml: `<h2>Informations légales</h2>
        <p><strong>Projet libre et gratuit.</strong> Cette appli est un projet amateur, sans but commercial. Son auteur ne revendique aucune paternité ni aucun droit sur le code et les listes : tu peux les copier, les modifier et les réutiliser librement, sans rien demander (<a href="https://creativecommons.org/publicdomain/zero/1.0/deed.fr" target="_blank" rel="noopener">dédicace au domaine public, CC0 1.0</a>).</p>
        <p><strong>Ce qui n'est pas couvert</strong> : la carte de l'île, réalisée par Gaëtan Mineau pour l'Association Naturaliste d'Ouessant, reste leur œuvre ; la météo vient de <a href="https://open-meteo.com/" target="_blank" rel="noopener">Open-Meteo.com</a> ; les polices Spectral et Public Sans sont sous licence SIL Open Font License. Le classement des espèces a été établi à la main d'après des données de Faune France ; l'appli n'interroge pas leur base.</p>
        <p><strong>Pas de garantie.</strong> Les positions des lieux-dits sont indicatives et les listes peuvent contenir des erreurs. Ne t'y fie pas pour ta sécurité ou pour naviguer.</p>
        <p><strong>Vie privée.</strong> Pas de compte, pas de cookies, pas de statistiques. Ta position GPS n'est utilisée que sur ton appareil et n'est envoyée nulle part, sauf si tu choisis de la partager. Ton thème et ta langue sont mémorisés dans ton navigateur. Les polices sont hébergées avec l'appli : seule la météo est demandée à un service extérieur (Open-Meteo), qui voit donc ton adresse IP. Si tu proposes un nouvel oiseau dans l’éditeur, le nom saisi est envoyé à iNaturalist pour retrouver les autres noms. Si tu envoies une proposition, elle passe par un formulaire Google.</p>`,
      badFile: "Ce fichier n'est pas lisible. Il doit contenir une liste d'espèces avec au moins les champs « Nom Français », « Nom Scientifique » et « Proposition de Canal de Diffusion Ouessant ».",
      channels: { telegram: 'Alerte Telegram', whatsapp: 'Alerte WhatsApp', none: "Pas d'alerte", unknown: 'Non renseigné' },
      tabBirds: 'Oiseaux', tabPlaces: 'Lieux', tabWhere: 'Où suis-je ?',
      phareLabel: 'Météo et partage', phareOff: 'Hors connexion : le phare est éteint (météo indisponible)', wOffline: 'Pas de connexion : la météo reviendra avec le réseau.', wTitle: 'Météo à Ouessant', wLoading: 'Chargement de la météo…', wErr: 'Météo indisponible pour le moment (connexion ?).',
      wNow: (dir, kmh, bf) => `Vent ${dir}, ${kmh} km/h (force ${bf})`, wGust: g => `rafales ${g} km/h`, wSrc: 'Météo : Open-Meteo.com, mise à jour toutes les 15 minutes.',
      dirs16: ['du nord','du nord-nord-est','du nord-est',"d'est-nord-est","d'est","d'est-sud-est",'du sud-est','du sud-sud-est','du sud','du sud-sud-ouest','du sud-ouest',"d'ouest-sud-ouest","d'ouest","d'ouest-nord-ouest",'du nord-ouest','du nord-nord-ouest'],
      dirsShort: ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSO','SO','OSO','O','ONO','NO','NNO'],
      today: "Aujourd'hui", tomorrow: 'Demain',
      rTelegram: '<b>Telegram</b>, en général : les raretés à l’échelle nationale.',
      rWhatsapp: '<b>WhatsApp</b>, en général : les raretés locales, les espèces peu communes sur l’île et le suivi des raretés déjà annoncées.',
      rNone: '<b>Pas d’alerte</b>, en général : les espèces communes ou nicheuses à Ouessant.',
      ruleBtn: 'Proposer une nouvelle règle', ruleTpl: 'Proposition de règles pour les canaux :\nTelegram : \nWhatsApp : ',
      cTitle: 'Quel canal ?', cTelegram: '<b>Telegram</b> pour les raretés à l’échelle nationale',
      cWhatsapp: '<b>WhatsApp</b> pour les raretés locales, les espèces peu communes sur l’île et le suivi des raretés déjà annoncées',
      cNone: '<b>Rien</b> pour les espèces communes ou nicheuses à Ouessant',
      shTitle: "Partager l'appli", shText: "Fais scanner ce QR code à un autre observateur : il ouvrira l'appli directement.",
      shBtn: 'Partager…', shCopy: 'Copier le lien', shCopied: 'Lien copié !', qrErr: 'QR code indisponible hors connexion.',
      egg: n => `Alerte Telegram ! ${n} vient de passer devant le phare du Créac'h.`, eggNone: "Un oiseau vient de passer devant le phare du Créac'h !",
      wx: { 0: 'ciel dégagé', 1: 'peu nuageux', 2: 'partiellement nuageux', 3: 'couvert', 45: 'brouillard', 48: 'brouillard givrant', 51: 'bruine légère', 53: 'bruine', 55: 'bruine forte',
            56: 'bruine verglaçante', 57: 'bruine verglaçante', 61: 'pluie faible', 63: 'pluie', 65: 'forte pluie', 66: 'pluie verglaçante', 67: 'pluie verglaçante',
            71: 'neige faible', 73: 'neige', 75: 'forte neige', 77: 'grains de neige', 80: 'averses', 81: 'averses', 82: 'fortes averses', 85: 'averses de neige', 86: 'averses de neige',
            95: 'orage', 96: 'orage avec grêle', 99: 'orage avec grêle' },
      prefsLabel: 'Affichage', themeLabel: 'Thème', tAuto: 'Auto', tLight: 'Clair', tDark: 'Sombre',
      colorsLabel: 'Couleurs', cStd: 'Standard', cCvd: 'Daltonisme',
      cvdNote: "« Daltonisme » utilise des couleurs distinguables par la plupart des personnes daltoniennes. « Auto » suit le réglage du téléphone.",
      ledeWhere: 'Trouve les lieux-dits les plus proches de ta position.',
      locateBtn: 'Me localiser', relocateBtn: 'Actualiser ma position',
      alertOff: 'Tu n’es pas sur l’île d’Ouessant : tu ne peux donc pas signaler cet oiseau.',
      alertImprecise: m => `Position trop imprécise (± ${m} m) pour savoir où tu es. Sors à découvert, vérifie que la localisation « précise » est activée, attends quelques secondes puis réessaie.`,
      alertApprox: m => `Position approximative (± ${m} m) : le lieu-dit peut être faux. Message copié ; tu peux réessayer à découvert.`,
      coarseHtml: m => `<p><strong>Tu n’as pas partagé ta position exacte</strong> (précision ± ${m} m, soit une zone de plusieurs kilomètres). Les résultats seraient faux, donc l’appli ne les affiche pas.</p>
        <p>Pour partager ta position <strong>précise</strong>, dans Chrome : menu <strong>⋮</strong> → <strong>Paramètres</strong> → <strong>Paramètres des sites</strong> → <strong>Position</strong> → dans la liste « Autorisé », touche ce site → choisis <strong>Exacte</strong> (au lieu d’Approximative) → <strong>Confirmer</strong>. Reviens ensuite sur l’appli, recharge la page et touche à nouveau le bouton.</p>`,
      retry: 'Réessayer', gpsLow: 'Précision faible : sors à découvert, vérifie que la localisation « précise » est activée, puis actualise.',
      alertHint: 'Préparer le message d’alerte', openWhatsapp: 'Ouvrir WhatsApp', openTelegram: 'Ouvrir Telegram',
      stayQ: 'L’oiseau stationne depuis plusieurs jours ? Annonce-le plutôt sur WhatsApp, même s’il est très rare.', stayWa: 'Envoyer sur WhatsApp',
      alertCopied: 'Message copié. Ouvre l’appli, choisis le bon groupe et colle-le.', alertCopyFail: 'Copie automatique impossible : appuie sur « Copier ».',
      alertNoGps: 'Position GPS indisponible : le message ne contient que l’espèce. Autorise la localisation pour l’ajouter.',
      alertMsg: (fr, sci, pos, place) => [`${fr} (${sci})`, pos && `GPS : ${pos}`, place && `Lieu-dit le plus proche : ${place}`].filter(Boolean).join('\n'),
      shareLocBtn: 'Partager ma position', shareLocCopied: 'Message copié !',
      shareLocMsg: (name, lat, lon, url) => `GPS : ${lat}, ${lon}\n${url}\nLieu-dit le plus proche : ${name}`,
      youAre: (c, a, n) => `Tu es dans le carré ${c} (précision GPS ± ${a} m). Les ${n} lieux-dits les plus proches :`,
      nearLabel: 'Lieux-dits affichés',
      notHere: d => `Tu ne sembles pas être sur Ouessant : le lieu-dit le plus proche est à ${d}.`,
      dirs: ['N', 'NE', 'E', 'SE', 'S', 'SO', 'O', 'NO'],
      checkedShort: 'position vérifiée',
      whereCaption: c => `Ta position (point ${window.OUESSANT_ETAT.cvd ? 'rose' : 'bleu'}) dans le carré ${c}, et les lieux-dits numérotés.`,
      whereNote: "Les distances sont approximatives : la plupart des lieux-dits sont placés au centre de leur carré sur la carte (± 100 m). Ta position n'est envoyée nulle part.",
      ledePlaces: "Cherche un lieu-dit de l'île pour obtenir ses coordonnées GPS <strong>INDICATIVES</strong>.",
      locTip: "« Loc SVP » reste le meilleur moyen de savoir où aller.",
      openIslandMap: "Ouvrir la carte de l'île (PDF)",
      mapCaption: c => `${c.length > 1 ? 'Carrés' : 'Carré'} ${c.join(', ')} encadré${c.length > 1 ? 's' : ''} en ${window.OUESSANT_ETAT.cvd ? 'bleu' : 'rouge'}, extrait de la carte de l'Association Naturaliste d'Ouessant.`,
      mapLoading: 'Chargement de la carte…',
      verified: 'Position vérifiée sur le terrain',
      suggest: 'Proposer une meilleure position',
      sHelp: "Le nouveau point doit se trouver dans l'un des carrés affichés ci-dessus.",
      useGps: 'Utiliser ma position GPS (sur place)',
      gpsWait: 'Recherche de ta position…',
      gpsErr: 'Position GPS indisponible. Autorise la localisation ou colle des coordonnées.',
      gpsAcc: m => `Position GPS obtenue (précision ± ${m} m).` + (m > 100 ? ' Précision faible : attends quelques secondes à découvert et réessaie.' : ''),
      pasteLabel: 'ou colle des coordonnées',
      commentLabel: 'Commentaire (facultatif)',
      check: 'Vérifier le point',
      badFormat: 'Coordonnées illisibles. Exemple : 48.45606, -5.08603',
      okIn: (c, d) => `Le point est bien dans la zone (carré ${c}), à ${d} de la position actuelle.`,
      outZone: (c, n) => c ? `Ce point est dans le carré ${c}, en dehors des carrés affichés : il est trop loin de « ${n} ». Vérifie les coordonnées.` : "Ce point est en dehors de la carte d'Ouessant. Vérifie les coordonnées.",
      sendOff: "L'envoi des propositions est momentanément indisponible.",
      sendForm: 'Envoyer la proposition',
      adminMode: 'Mode admin', adminModeT: 'Clé Admin active : la gérer ou l’oublier', proposeEdit: 'Proposer une modification', proposeCanal: 'Proposer un autre canal', lockedSp: 'Espèce commune, verrouillée : pas de modification possible', newBird: 'Proposer un nouvel oiseau', newBirdQ: 'Proposer cet oiseau ?',
      bHelpEdit: 'Corrige les champs nécessaires, puis prépare la proposition. Explique ton choix en commentaire si besoin.',
      bHelpNew: 'Une espèce ou sous-espèce manque à la liste ? Renseigne-la : elle sera ajoutée après vérification.',
      fFR: 'Nom français', fSCI: 'Nom scientifique', fEN: 'Nom anglais (facultatif)', fType: 'Type de taxon', fCanal: 'Canal de diffusion',
      typeSp: 'espèce', typeSsp: 'sous-espèce', choose: '— choisir —', prep: 'Préparer la proposition',
      needFrSci: 'Le nom français et le nom scientifique sont obligatoires.', needCanal: 'Choisis un canal de diffusion.',
      noChange: 'Aucune modification : change au moins un champ, ou explique-toi en commentaire.',
      bDup: n => `« ${n} » est déjà dans la liste. Cherche-le, puis utilise « Proposer une modification ».`,
      bClash: n => `Ce nom est déjà utilisé par « ${n} ».`,
      changes: 'Modifications proposées :', commentOnly: 'Aucun champ modifié : seul ton commentaire sera envoyé.',
      bNewOk: n => `« ${n} » est prêt à être proposé.`,
      newPlace: 'Proposer un nouveau lieu-dit', newPlaceQ: 'Proposer ce lieu-dit ?',
      newHelp: "Un lieu-dit manque à la liste ? Donne son nom et sa position : il sera ajouté après vérification.",
      newName: 'Nom du lieu-dit',
      newNoName: 'Indique le nom du lieu-dit.',
      newDup: n => `« ${n} » est déjà dans la liste. Pour corriger sa position, ouvre-le et utilise « Proposer une meilleure position ».`,
      newOut: "Ce point est en dehors de la carte d'Ouessant. Vérifie les coordonnées.",
      newOk: (n, c) => `« ${n} » serait placé dans le carré ${c}. Vérifie sur la carte ci-dessous, puis envoie ta proposition.`,
      newCaption: (n, c) => `Position proposée pour « ${n} » (losange vert), carré ${c}.`,
      formNote: "Le formulaire va s'ouvrir, déjà rempli : il ne reste qu'à cliquer sur « Envoyer ». Ta proposition sera vérifiée, puis la mise à jour sera prise en compte dans les prochains jours.",
      mapMissing: "Aperçu indisponible : le fichier carte_ouessant.jpg est introuvable à côté de l'appli.",
      pPlaceholder: 'Nom du lieu (ex. Pern, Stiff, Kadoran)', pLabel: 'Rechercher un lieu',
      pCount: n => n + ' lieu' + (n>1?'x':''), pNone: q => `Aucun lieu ne correspond à « ${q} ».`,
      square: n => n > 1 ? 'Carrés' : 'Carré', approx: m => `Position approximative : ± ${m} m (centre du carré sur la carte)`,
      approxPlaced: m => `Position approximative : ± ${m} m (point placé sur la carte, non vérifié sur le terrain)`,
      exact: 'Position exacte', copy: 'Copier', copied: 'Copié !', openMap: 'Ouvrir dans Maps',
      placesNote: "Coordonnées calculées d'après la carte de l'île de l'Association Naturaliste d'Ouessant : chaque lieu est placé au centre de son carré, d'où une précision d'environ 500 m. Seuls les phares ont une position exacte. Vérifie sur le terrain avant de donner un point précis."
    },
    en: {
      docTitle: 'Birds of Ouessant · where to report',
      title: 'Birds of Ouessant',
      lede: 'Type a species name to find out which channel to report your sighting, then tap the channel to prepare your message.',
      placeholder: 'English, French or scientific name',
      searchLabel: 'Search for a species',
      clear: 'Clear', all: 'All', showSsp: 'Show subspecies', ssp: 'subspecies',
      channelsLabel: 'Filter by reporting channel',
      loading: 'Loading the species list…',
      found: 'Species found', noMatch: 'No matching species yet.',
      near: n => n + ' similar name' + (n>1?'s':''),
      count: (n, filtered) => n + (n>1 ? ' taxa' : ' taxon') + (filtered ? ' on this channel' : ''),
      fuzzyNear: q => `No species is called exactly “${q}”. Check the spelling against the similar names below. If it is none of them, it would probably be a first for the island: <strong>report it on Telegram</strong>.`,
      fuzzyNone: q => `“${q}” is not on the list of species already recorded on the island. Check the spelling; if it is correct, it would probably be a first for Ouessant: <strong>report it on Telegram</strong>.`,
      sourceGithub: 'Up-to-date list', listsOf: d => `lists of ${d}`, listsOfBoth: (b, p) => `birds of ${b}, places of ${p}`, sourceSaved: 'Copy saved in this browser', sourceFile: 'Imported file',
      sourceCount: (sp, ssp) => sp + ' species' + (ssp ? ' and ' + ssp + ' subspecies' : ''),
      importTitle: 'Add the species list',
      importText: 'The list could not be downloaded from GitHub on this page. Import the <em>ouessant_birds.json</em> file from your computer or phone: it will stay saved in this browser.',
      importBtn: 'Import the JSON file', legalBtn: 'Legal information', guideLink: 'User guide (PDF, in French)', editorLinkT: 'List editor', contactLink: 'A question or feedback?', contactLabel: 'Your message (question, idea, problem…)', contactSend: 'Continue to the form', contactHelp: 'Your message is anonymous. The form opens with your message already filled in: just click “Submit”. If you would like a reply, say in your message how to reach you.', contactEmpty: 'Write your message first.', azLabel: 'Jump to letter',
      legalHtml: `<h2>Legal information</h2>
        <p><strong>Free and open project.</strong> This app is an amateur project with no commercial purpose. Its author claims no authorship and no rights over the code and the lists: you can copy, modify and reuse them freely, without asking (<a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank" rel="noopener">public domain dedication, CC0 1.0</a>).</p>
        <p><strong>Not covered</strong>: the island map, made by Gaëtan Mineau for the Association Naturaliste d'Ouessant, remains their work; the weather comes from <a href="https://open-meteo.com/" target="_blank" rel="noopener">Open-Meteo.com</a>; the Spectral and Public Sans fonts are under the SIL Open Font License. The species ranking was made by hand from Faune France data; the app does not query their database.</p>
        <p><strong>No warranty.</strong> Place positions are indicative and the lists may contain errors. Do not rely on them for your safety or for navigation.</p>
        <p><strong>Privacy.</strong> No account, no cookies, no analytics. Your GPS position is only used on your device and is sent nowhere, unless you choose to share it. Your theme and language are remembered in your browser. The fonts are hosted with the app: only the weather is requested from an outside service (Open-Meteo), which therefore sees your IP address. If you suggest a new bird in the editor, the name you type is sent to iNaturalist to find the other names. If you send a suggestion, it goes through a Google form.</p>`,
      badFile: 'This file cannot be read. It must contain a list of species with at least the fields “Nom Français”, “Nom Scientifique” and “Proposition de Canal de Diffusion Ouessant”.',
      channels: { telegram: 'Telegram alert', whatsapp: 'WhatsApp alert', none: 'No alert', unknown: 'Not specified' },
      tabBirds: 'Birds', tabPlaces: 'Places', tabWhere: 'Where am I?',
      phareLabel: 'Weather and sharing', phareOff: 'Offline: the lighthouse is off (no weather)', wOffline: 'No connection: the weather will be back with the network.', wTitle: 'Weather on Ouessant', wLoading: 'Loading the weather…', wErr: 'Weather unavailable right now (connection?).',
      wNow: (dir, kmh, bf) => `Wind ${dir}, ${kmh} km/h (force ${bf})`, wGust: g => `gusts ${g} km/h`, wSrc: 'Weather: Open-Meteo.com, updated every 15 minutes.',
      dirs16: ['from the N','from the NNE','from the NE','from the ENE','from the E','from the ESE','from the SE','from the SSE','from the S','from the SSW','from the SW','from the WSW','from the W','from the WNW','from the NW','from the NNW'],
      dirsShort: ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW'],
      today: 'Today', tomorrow: 'Tomorrow',
      rTelegram: '<b>Telegram</b>, usually: rarities at national level.',
      rWhatsapp: '<b>WhatsApp</b>, usually: local rarities, species that are scarce on the island, and following up rarities already reported.',
      rNone: '<b>No alert</b>, usually: species that are common or breed on Ouessant.',
      ruleBtn: 'Suggest a new rule', ruleTpl: 'Suggested channel rules:\nTelegram: \nWhatsApp: ',
      cTitle: 'Which channel?', cTelegram: '<b>Telegram</b> for rarities at national level',
      cWhatsapp: '<b>WhatsApp</b> for local rarities, species that are scarce on the island, and following up rarities already reported',
      cNone: '<b>Nothing</b> for species that are common or breed on Ouessant',
      shTitle: 'Share the app', shText: 'Let another birder scan this QR code: it opens the app straight away.',
      shBtn: 'Share…', shCopy: 'Copy link', shCopied: 'Link copied!', qrErr: 'QR code unavailable offline.',
      egg: n => `Telegram alert! ${n} just flew past the Créac'h lighthouse.`, eggNone: "A bird just flew past the Créac'h lighthouse!",
      wx: { 0: 'clear sky', 1: 'mainly clear', 2: 'partly cloudy', 3: 'overcast', 45: 'fog', 48: 'freezing fog', 51: 'light drizzle', 53: 'drizzle', 55: 'heavy drizzle',
            56: 'freezing drizzle', 57: 'freezing drizzle', 61: 'light rain', 63: 'rain', 65: 'heavy rain', 66: 'freezing rain', 67: 'freezing rain',
            71: 'light snow', 73: 'snow', 75: 'heavy snow', 77: 'snow grains', 80: 'showers', 81: 'showers', 82: 'heavy showers', 85: 'snow showers', 86: 'snow showers',
            95: 'thunderstorm', 96: 'thunderstorm with hail', 99: 'thunderstorm with hail' },
      prefsLabel: 'Display', themeLabel: 'Theme', tAuto: 'Auto', tLight: 'Light', tDark: 'Dark',
      colorsLabel: 'Colours', cStd: 'Standard', cCvd: 'Colour-blind',
      cvdNote: '“Colour-blind” uses colours most colour-blind people can tell apart. “Auto” follows your phone’s setting.',
      ledeWhere: 'Find the place names closest to where you are.',
      locateBtn: 'Locate me', relocateBtn: 'Update my position',
      alertOff: 'You are not on Ouessant: you cannot report this bird.',
      alertImprecise: m => `Position too imprecise (± ${m} m) to know where you are. Go out in the open, check that “precise” location is on, wait a few seconds and try again.`,
      alertApprox: m => `Approximate position (± ${m} m): the place name may be wrong. Message copied; you can try again in the open.`,
      coarseHtml: m => `<p><strong>You did not share your exact position</strong> (accuracy ± ${m} m, an area several kilometres wide). The results would be wrong, so the app does not show them.</p>
        <p>To share your <strong>precise</strong> position, in Chrome: menu <strong>⋮</strong> → <strong>Settings</strong> → <strong>Site settings</strong> → <strong>Location</strong> → in the “Allowed” list, tap this site → choose <strong>Exact</strong> (instead of Approximate) → <strong>Confirm</strong>. Then go back to the app, reload the page and tap the button again.</p>`,
      retry: 'Try again', gpsLow: 'Low accuracy: go out in the open, check that “precise” location is on, then update.',
      alertHint: 'Prepare the alert message', openWhatsapp: 'Open WhatsApp', openTelegram: 'Open Telegram',
      stayQ: 'Has the bird been staying for several days? Report it on WhatsApp instead, even if it is very rare.', stayWa: 'Send on WhatsApp',
      alertCopied: 'Message copied. Open the app, pick the right group and paste it.', alertCopyFail: 'Automatic copy failed: press “Copy”.',
      alertNoGps: 'GPS position unavailable: the message only contains the species. Allow location access to add it.',
      alertMsg: (fr, sci, pos, place) => [`${fr} (${sci})`, pos && `GPS: ${pos}`, place && `Closest place name: ${place}`].filter(Boolean).join('\n'),
      shareLocBtn: 'Share my position', shareLocCopied: 'Message copied!',
      shareLocMsg: (name, lat, lon, url) => `GPS: ${lat}, ${lon}\n${url}\nClosest place name: ${name}`,
      youAre: (c, a, n) => `You are in square ${c} (GPS accuracy ± ${a} m). The ${n} closest place names:`,
      nearLabel: 'Place names shown',
      notHere: d => `You don’t seem to be on Ouessant: the closest place name is ${d} away.`,
      dirs: ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'],
      checkedShort: 'position checked',
      whereCaption: c => `Your position (${window.OUESSANT_ETAT.cvd ? 'pink' : 'blue'} dot) in square ${c}, and the numbered place names.`,
      whereNote: 'Distances are approximate: most place names sit at the centre of their map square (± 100 m). Your position is not sent anywhere.',
      ledePlaces: 'Search for a place name on the island to get its <strong>INDICATIVE</strong> GPS coordinates.',
      locTip: 'Asking “Loc SVP” (location please) in the group is still the best way to know where to go.',
      openIslandMap: 'Open the island map (PDF)',
      mapCaption: c => `${c.length > 1 ? 'Squares' : 'Square'} ${c.join(', ')} outlined in ${window.OUESSANT_ETAT.cvd ? 'blue' : 'red'}, from the map by the Association Naturaliste d’Ouessant.`,
      mapLoading: 'Loading the map…',
      verified: 'Position checked on the ground',
      suggest: 'Suggest a better position',
      sHelp: 'The new point must lie within one of the squares shown above.',
      useGps: 'Use my GPS position (on site)',
      gpsWait: 'Getting your position…',
      gpsErr: 'GPS position unavailable. Allow location access or paste coordinates.',
      gpsAcc: m => `GPS position found (accuracy ± ${m} m).` + (m > 100 ? ' Low accuracy: wait a few seconds in the open and try again.' : ''),
      pasteLabel: 'or paste coordinates',
      commentLabel: 'Comment (optional)',
      check: 'Check the point',
      badFormat: 'Coordinates not recognised. Example: 48.45606, -5.08603',
      okIn: (c, d) => `The point is within the area (square ${c}), ${d} from the current position.`,
      outZone: (c, n) => c ? `This point is in square ${c}, outside the squares shown: it is too far from “${n}”. Check the coordinates.` : 'This point is outside the Ouessant map. Check the coordinates.',
      sendOff: 'Sending suggestions is temporarily unavailable.',
      sendForm: 'Send the suggestion',
      adminMode: 'Admin mode', adminModeT: 'Admin key active: manage or forget it', proposeEdit: 'Suggest a change', proposeCanal: 'Suggest another channel', lockedSp: 'Common species, locked: no changes possible', newBird: 'Suggest a new bird', newBirdQ: 'Suggest this bird?',
      bHelpEdit: 'Correct the fields as needed, then prepare the suggestion. Explain your choice in a comment if useful.',
      bHelpNew: 'Is a species or subspecies missing from the list? Fill it in: it will be added after checking.',
      fFR: 'French name', fSCI: 'Scientific name', fEN: 'English name (optional)', fType: 'Taxon type', fCanal: 'Reporting channel',
      typeSp: 'species', typeSsp: 'subspecies', choose: '— choose —', prep: 'Prepare the suggestion',
      needFrSci: 'The French and scientific names are required.', needCanal: 'Choose a reporting channel.',
      noChange: 'No change: edit at least one field, or explain in a comment.',
      bDup: n => `“${n}” is already on the list. Search for it, then use “Suggest a change”.`,
      bClash: n => `This name is already used by “${n}”.`,
      changes: 'Suggested changes:', commentOnly: 'No field changed: only your comment will be sent.',
      bNewOk: n => `“${n}” is ready to be suggested.`,
      newPlace: 'Suggest a new place name', newPlaceQ: 'Suggest this place name?',
      newHelp: 'Is a place name missing from the list? Give its name and position: it will be added after checking.',
      newName: 'Place name',
      newNoName: 'Enter the place name.',
      newDup: n => `“${n}” is already on the list. To correct its position, open it and use “Suggest a better position”.`,
      newOut: 'This point is outside the Ouessant map. Check the coordinates.',
      newOk: (n, c) => `“${n}” would be placed in square ${c}. Check on the map below, then send your suggestion.`,
      newCaption: (n, c) => `Suggested position for “${n}” (green diamond), square ${c}.`,
      formNote: 'The form will open already filled in: just press “Submit”. Your suggestion will be checked, and the update will be applied within the next few days.',
      mapMissing: 'Preview unavailable: the file carte_ouessant.jpg cannot be found next to the app.',
      pPlaceholder: 'Place name (e.g. Pern, Stiff, Kadoran)', pLabel: 'Search for a place',
      pCount: n => n + ' place' + (n>1?'s':''), pNone: q => `No place matches “${q}”.`,
      square: n => n > 1 ? 'Squares' : 'Square', approx: m => `Approximate position: ± ${m} m (centre of the map square)`,
      approxPlaced: m => `Approximate position: ± ${m} m (point placed on the map, not checked on the ground)`,
      exact: 'Exact position', copy: 'Copy', copied: 'Copied!', openMap: 'Open in Maps',
      placesNote: 'Coordinates derived from the island map by the Association Naturaliste d’Ouessant: each place sits at the centre of its map square, so accuracy is about 500 m. Only the lighthouses have an exact position. Check on the ground before giving a precise spot.'
    }
  };
